import express from 'express';
import cors from 'cors';
import morgan from 'morgan';
import { register, login } from './controllers/authController.js';
import authRoutes from './routes/authRoutes.js';
import userRoutes from './routes/userRoutes.js';
import dashboardRoutes from './routes/dashboardRoutes.js';
import grnRoutes from './routes/grnRoutes.js';
import invoiceRoutes from './routes/invoiceRoutes.js';
import { salesRoutes, purchaseRoutes } from './routes/orderRoutes.js';
import healthRoutes from './routes/healthRoutes.js';
import { productRoutes, partyRoutes } from './routes/simpleRoutes.js';
import Product from './models/Product.js';
import { Customer, Supplier } from './models/Party.js';
import { notFound, errorHandler } from './middleware/error.js';

const app = express();
app.use(cors({ origin: process.env.CLIENT_URL || '*' }));
app.use(express.json({ limit: '1mb' }));
app.use(morgan('dev'));
app.get('/', (req, res) => res.json({ name: 'ERP Management API', version: '1.0.0' }));
app.use('/api/health', healthRoutes);
app.use('/api/auth', authRoutes);
app.post('/api/register', register);
app.post('/api/login', login);
app.use('/api/users', userRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use('/api/products', productRoutes(Product));
app.use('/api/customers', partyRoutes(Customer, ['Admin', 'Sales']));
app.use('/api/suppliers', partyRoutes(Supplier, ['Admin', 'Purchase']));
app.use('/api/sales-orders', salesRoutes());
app.use('/api/purchase-orders', purchaseRoutes());
app.use('/api/grn', grnRoutes);
app.use('/api/invoices', invoiceRoutes);
app.use(notFound);
app.use(errorHandler);
export default app;
